
# Data Source Configuration
spring.datasource.url=jdbc:mysql://staging-mysql-db.cncc8o8a48qh.us-west-1.rds.amazonaws.com:3306/production_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}