name: Build, Test, and Push Backend Docker Image

on:
  push:
    branches: [ test-cicd-backend ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 1: Securely recreate your .env file from your GitHub Secret on the runner
      - name: Create .env file for database tests
        run: |
          echo "${{ secrets.ENV_FILE_DB }}" > .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_TEST_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_SECRETS_KEYS }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 2: Run backend tests AND package the application into a .jar file
      - name: Run Backend Integration Tests and Package
        env:
          ENV_FILE_DB: ${{ secrets.ENV_FILE_DB }}
        run: |
          mvn clean package

      # Step 3: Build the Docker image
      - name: Docker build
        run: |
          docker build -t backend-test:latest .

      - name: Docker tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag backend-test:latest $ECR_REGISTRY/backend-test:${{ github.run_number }}
          docker tag backend-test:latest $ECR_REGISTRY/backend-test:latest

      - name: Docker push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/backend-test:${{ github.run_number }}
          docker push $ECR_REGISTRY/backend-test:latest