apiVersion: v1
kind: Service
metadata:
  name: bank-backend-service
spec:
  selector:
    # Must match the Deployment pod label so the Service gets endpoints.
    app: bank-backend
  ports:
    - protocol: TCP
      port: 8080   # The service port exposed internally
      targetPort: 8080  # Container port where your Spring Boot app listens
  type: ClusterIP  # Change LoadBalancer to ClusterIP
